export const towns_array = [
  'Kraków',
  'Warszawa',
  'Gdańsk',
  'Wrocław',
  'Bydgoszcz',
  'Katowice',
];

export const keywordsList = [
  'sale',
  'discount',
  'promotion',
  'clearance',
  'markdown',
  'deal',
  'savings',
  'bargain',
  'sales event',
  'flash sale',
  'limited time offer',
  'coupon',
  'voucher',
  'rebate',
  'bulk discount',
  'buy one get one',
  'free shipping',
  'seasonal sale',
  'holiday sale',
  'special offer',
  'reward points',
  'loyalty program',
  'customer retention',
  'upsell',
  'cross-sell',
  'conversion rate',
  'return on investment',
  'advertising',
  'marketing campaign',
  'target audience',
  'e-commerce',
  'online store',
  'retail',
  'wholesale',
];
